/**
 * GENERATED by `npm run gen:sword1-tables`. Do not edit by hand.
 *
 * What `fnPlaySequence <n>` names on disc. The scripts carry a *number* and
 * the names lived in Revolution's interpreter, so this project carries them —
 * ADR 0029's line, for the fifth table in this family.
 *
 * Broken Sword II needs no equivalent: its own `fnPlaySequence` takes the
 * filename as a pushed string, so the game carries it there.
 *
 * Read from ScummVM's `engines/sword1/animation.cpp`.
 */

/** Sequence number -> base filename, without an extension. */
export const SWORD1_SEQUENCE_NAMES: readonly string[] = [
  'ferrari',
  'ladder',
  'steps',
  'sewer',
  'intro',
  'river',
  'truck',
  'grave',
  'montfcon',
  'tapestry',
  'ireland',
  'finale',
  'history',
  'spanish',
  'well',
  'candle',
  'geodrop',
  'vulture',
  'enddemo',
  'credits',
  'finale',
];

/** The name for a sequence number, or null when there is none. */
export function sword1SequenceName(sequence: number): string | null {
  return SWORD1_SEQUENCE_NAMES[sequence] ?? null;
}
