import { describe, expect, it } from 'vitest';
import { Codec47Decoder } from '../src/engine/video/codec47.js';

/** A codec 47 frame header: 26 bytes, then the payload. */
function frame(kind: number, { seq = 0, rotation = 0, flags = 0 } = {}, payload: number[] = []) {
  const header = new Uint8Array(26);
  new DataView(header.buffer).setUint16(0, seq, true);
  header[2] = kind;
  header[3] = rotation;
  header[4] = flags;
  return new Uint8Array([...header, ...payload]);
}

/**
 * SMUSH codec 47.
 *
 * The workhorse: three block sizes, motion vectors, and a generated glyph table
 * of two hundred and fifty-six two-colour edge patterns.
 *
 * **Tier 1 only, and #101 must not close on these.** The glyph table is
 * generated by reproducing the reference's construction, so a fixture written
 * from the same reading agrees with a decoder built from it whether or not
 * either is right — and a wrong table puts edges in the wrong places, which
 * reads as a slightly soft picture rather than as a fault. That is precisely
 * the shape of the four v6 faults `verifying-version-support.md` records. Only
 * a demo's own `.SAN` settles it.
 */
describe('codec 47', () => {
  it('takes a whole keyframe as it is', () => {
    const decoder = new Codec47Decoder(4, 4);
    const pixels = Array.from({ length: 16 }, (_, i) => i + 1);
    const out = new Uint8Array(16);

    expect(decoder.decode(frame(0, {}, pixels), out)).toBe(true);
    expect([...out]).toEqual(pixels);
  });

  it('seeds both delta buffers from the header on the first frame', () => {
    // Sequence zero carries the two fill colours. Without them the first
    // motion-compensated frame references whatever the buffers happened to
    // hold.
    const decoder = new Codec47Decoder(8, 8);
    const first = frame(0, { seq: 0 });
    first[12] = 3;
    first[13] = 4;

    const out = new Uint8Array(64);
    expect(decoder.decode(first, out)).toBe(true);
  });

  it('fills a block with one colour', () => {
    const decoder = new Codec47Decoder(8, 8);
    const out = new Uint8Array(64);

    // Sub-codec 2, sequence 1 so it follows sequence 0.
    decoder.decode(frame(0, { seq: 0 }), out);
    expect(decoder.decode(frame(2, { seq: 1 }, [0xfe, 7]), out)).toBe(true);
    expect([...out]).toEqual(new Array(64).fill(7));
  });

  it('subdivides an 8x8 block into four 4x4 blocks', () => {
    const decoder = new Codec47Decoder(8, 8);
    const out = new Uint8Array(64);

    decoder.decode(frame(0, { seq: 0 }), out);
    // Subdivide, then fill each quarter with a different colour.
    decoder.decode(frame(2, { seq: 1 }, [0xff, 0xfe, 1, 0xfe, 2, 0xfe, 3, 0xfe, 4]), out);

    expect(out[0]).toBe(1);
    expect(out[4]).toBe(2);
    expect(out[8 * 4]).toBe(3);
    expect(out[8 * 4 + 4]).toBe(4);
  });

  it('reads four literal pixels at the smallest block size', () => {
    // 2x2 is the floor: a subdivide there means literals, not further
    // recursion. Recursing instead would consume the rest of the frame.
    const decoder = new Codec47Decoder(8, 8);
    const out = new Uint8Array(64);

    decoder.decode(frame(0, { seq: 0 }), out);
    decoder.decode(
      frame(
        2,
        { seq: 1 },
        [0xff, 0xff, 0xff, 9, 8, 7, 6, 0xfe, 0, 0xfe, 0, 0xfe, 0, 0xfe, 0, 0xfe, 0],
      ),
      out,
    );

    expect(out[0]).toBe(9);
    expect(out[1]).toBe(8);
    expect(out[8]).toBe(7);
    expect(out[9]).toBe(6);
  });

  it('draws a glyph as two colours either side of a generated edge', () => {
    const decoder = new Codec47Decoder(8, 8);
    const out = new Uint8Array(64);

    decoder.decode(frame(0, { seq: 0 }), out);
    // Glyph 0, inside colour 1, outside colour 2.
    expect(decoder.decode(frame(2, { seq: 1 }, [0xfd, 0, 1, 2]), out)).toBe(true);

    // Both colours appear: the glyph is a partition, not a fill.
    expect([...out]).toContain(1);
    expect([...out]).toContain(2);
  });

  it('builds 256 glyphs at each block size', () => {
    // Sixteen border points squared. A table of any other size means the
    // construction diverged from the reference.
    const decoder = new Codec47Decoder(8, 8);
    const out = new Uint8Array(64);
    decoder.decode(frame(0, { seq: 0 }), out);

    // Glyph 255 must resolve rather than fall off the end of the table.
    expect(decoder.decode(frame(2, { seq: 1 }, [0xfd, 255, 1, 2]), out)).toBe(true);
  });

  it('reuses a whole previous frame for sub-codecs 3 and 4', () => {
    const decoder = new Codec47Decoder(4, 4);
    const out = new Uint8Array(16);

    decoder.decode(frame(0, {}, new Array(16).fill(5)), out);
    expect(decoder.decode(frame(3), out)).toBe(true);
    expect(decoder.decode(frame(4), out)).toBe(true);
  });

  it('decodes a run-length frame for sub-codec 5', () => {
    const decoder = new Codec47Decoder(4, 4);
    const out = new Uint8Array(16);
    const f = frame(5, {}, [31, 6]);
    new DataView(f.buffer).setUint32(14, 16, true);

    expect(decoder.decode(f, out)).toBe(true);
    expect([...out]).toEqual(new Array(16).fill(6));
  });

  it('refuses sub-codec 1, which ScummVM records as Outlaws’ and no SCUMM game uses', () => {
    const decoder = new Codec47Decoder(4, 4);
    expect(decoder.decode(frame(1), new Uint8Array(16))).toBe(false);
  });

  it('refuses a frame too short to hold a header', () => {
    const decoder = new Codec47Decoder(4, 4);
    expect(decoder.decode(new Uint8Array(8), new Uint8Array(16))).toBe(false);
  });

  it('survives a truncated payload instead of running off the end', () => {
    const decoder = new Codec47Decoder(8, 8);
    const out = new Uint8Array(64);
    decoder.decode(frame(0, { seq: 0 }), out);
    expect(() => decoder.decode(frame(2, { seq: 1 }, [0xff, 0xff]), out)).not.toThrow();
  });
});
