/**
 * What each SLUDGE command number is called.
 *
 * **Generated by `npm run gen:sludge-tables` — do not edit.** The names come
 * from `engines/sludge/csludge.h` in a ScummVM checkout, whose enum declares them with no
 * explicit values, so its declaration order is the numbering.
 *
 * 42 commands. The index is the number the bytecode carries.
 */
export const SLUDGE_COMMAND_NAMES: readonly string[] = [
  /*  0 */ 'unknown',
  /*  1 */ 'return',
  /*  2 */ 'branch',
  /*  3 */ 'brZero',
  /*  4 */ 'setGlobal',
  /*  5 */ 'setLocal',
  /*  6 */ 'loadGlobal',
  /*  7 */ 'loadLocal',
  /*  8 */ 'plus',
  /*  9 */ 'minus',
  /* 10 */ 'mult',
  /* 11 */ 'divide',
  /* 12 */ 'and',
  /* 13 */ 'or',
  /* 14 */ 'equals',
  /* 15 */ 'notEq',
  /* 16 */ 'modulus',
  /* 17 */ 'loadValue',
  /* 18 */ 'loadBuilt',
  /* 19 */ 'loadFunc',
  /* 20 */ 'callit',
  /* 21 */ 'loadString',
  /* 22 */ 'loadFile',
  /* 23 */ 'loadObjtype',
  /* 24 */ 'not',
  /* 25 */ 'loadNull',
  /* 26 */ 'stackPush',
  /* 27 */ 'lessthan',
  /* 28 */ 'morethan',
  /* 29 */ 'negative',
  /* 30 */ 'unreg',
  /* 31 */ 'lessEqual',
  /* 32 */ 'moreEqual',
  /* 33 */ 'incrementLocal',
  /* 34 */ 'decrementLocal',
  /* 35 */ 'incrementGlobal',
  /* 36 */ 'decrementGlobal',
  /* 37 */ 'indexset',
  /* 38 */ 'indexget',
  /* 39 */ 'incrementIndex',
  /* 40 */ 'decrementIndex',
  /* 41 */ 'quickPush',
];

/** `SLUDGE_COMMAND_NAMES.length`, named for the bound checks that want it. */
export const SLUDGE_COMMAND_COUNT = 42;

/** The command's name, or a number in angle brackets where there is none. */
export function sludgeCommandName(command: number): string {
  return SLUDGE_COMMAND_NAMES[command] ?? `<command ${command}>`;
}
