/**
 * GENERATED by `npm run gen:sword2-tables`. Do not edit by hand.
 *
 * The opcode table: what Broken Sword II's bytecode calls each of its machine
 * code routines. `CP_CALL_MCODE` carries the *number*, so the names live in
 * the interpreter rather than in the game — ADR 0029's exact case for a table
 * being ours.
 *
 * No arity column, and deliberately: the parameter count is encoded in the
 * instruction beside the opcode number, so it is read rather than tabled. That
 * is what makes this family's bytecode splittable into editable instructions
 * without a table from outside the game — the same property `sword1` has, and
 * the reason Decompilation is available for both.
 *
 * `fnPrepareMusic` appears at more than one index (100, 102). That is Revolution's own table and not a parse error, so it is kept:
 * collapsing the repeat would renumber every opcode after it.
 *
 * Read from ScummVM's `engines/sword2/interpreter.cpp`.
 */

/** The opcodes, indexed by the number `CP_CALL_MCODE` carries. */
export const SWORD2_OPCODE_NAMES: readonly string[] = [
  'fnTestFunction',
  'fnTestFlags',
  'fnRegisterStartPoint',
  'fnInitBackground',
  'fnSetSession',
  'fnBackSprite',
  'fnSortSprite',
  'fnForeSprite',
  'fnRegisterMouse',
  'fnAnim',
  'fnRandom',
  'fnPreLoad',
  'fnAddSubject',
  'fnInteract',
  'fnChoose',
  'fnWalk',
  'fnWalkToAnim',
  'fnTurn',
  'fnStandAt',
  'fnStand',
  'fnStandAfterAnim',
  'fnPause',
  'fnMegaTableAnim',
  'fnAddMenuObject',
  'fnStartConversation',
  'fnEndConversation',
  'fnSetFrame',
  'fnRandomPause',
  'fnRegisterFrame',
  'fnNoSprite',
  'fnSendSync',
  'fnUpdatePlayerStats',
  'fnPassGraph',
  'fnInitFloorMouse',
  'fnPassMega',
  'fnFaceXY',
  'fnEndSession',
  'fnNoHuman',
  'fnAddHuman',
  'fnWeWait',
  'fnTheyDoWeWait',
  'fnTheyDo',
  'fnWalkToTalkToMega',
  'fnFadeDown',
  'fnISpeak',
  'fnTotalRestart',
  'fnSetWalkGrid',
  'fnSpeechProcess',
  'fnSetScaling',
  'fnStartEvent',
  'fnCheckEventWaiting',
  'fnRequestSpeech',
  'fnGosub',
  'fnTimedWait',
  'fnPlayFx',
  'fnStopFx',
  'fnPlayMusic',
  'fnStopMusic',
  'fnSetValue',
  'fnNewScript',
  'fnGetSync',
  'fnWaitSync',
  'fnRegisterWalkGrid',
  'fnReverseMegaTableAnim',
  'fnReverseAnim',
  'fnAddToKillList',
  'fnSetStandbyCoords',
  'fnBackPar0Sprite',
  'fnBackPar1Sprite',
  'fnForePar0Sprite',
  'fnForePar1Sprite',
  'fnSetPlayerActionEvent',
  'fnSetScrollCoordinate',
  'fnStandAtAnim',
  'fnSetScrollLeftMouse',
  'fnSetScrollRightMouse',
  'fnColor',
  'fnFlash',
  'fnPreFetch',
  'fnGetPlayerSaveData',
  'fnPassPlayerSaveData',
  'fnSendEvent',
  'fnAddWalkGrid',
  'fnRemoveWalkGrid',
  'fnCheckForEvent',
  'fnPauseForEvent',
  'fnClearEvent',
  'fnFaceMega',
  'fnPlaySequence',
  'fnShadedSprite',
  'fnUnshadedSprite',
  'fnFadeUp',
  'fnDisplayMsg',
  'fnSetObjectHeld',
  'fnAddSequenceText',
  'fnResetGlobals',
  'fnSetPalette',
  'fnRegisterPointerText',
  'fnFetchWait',
  'fnRelease',
  'fnPrepareMusic',
  'fnSoundFetch',
  'fnPrepareMusic',
  'fnSmackerLeadIn',
  'fnSmackerLeadOut',
  'fnStopAllFx',
  'fnCheckPlayerActivity',
  'fnResetPlayerActivityDelay',
  'fnCheckMusicPlaying',
  'fnPlayCredits',
  'fnSetScrollSpeedNormal',
  'fnSetScrollSpeedSlow',
  'fnRemoveChooser',
  'fnSetFxVolAndPan',
  'fnSetFxVol',
  'fnRestoreGame',
  'fnRefreshInventory',
  'fnChangeShadows',
];

/** How many opcodes the table declares. A call above this is a decoding fault. */
export const SWORD2_OPCODE_COUNT = SWORD2_OPCODE_NAMES.length;

/** `fnWalk` for 16, or `opcode<n>` when the number is outside the table. */
export function sword2OpcodeName(number: number): string {
  return SWORD2_OPCODE_NAMES[number] ?? `opcode${number}`;
}
