/**
 * GENERATED by `npm run gen:sword1-tables`. Do not edit by hand.
 *
 * What each mcode calls its six arguments, so an editor can show a call as
 * named operands rather than as a row of numbers. `IT_MCODE` carries the
 * argument *count*; what the arguments *mean* lived in Revolution's
 * interpreter, which is ADR 0029's case for a table being ours and generated.
 *
 * An empty string is an argument the source names with a placeholder letter —
 * `a`, `b`, `c`, `d`, `e`, `f`, `z`, or a trailing `x`. It is kept in the
 * row rather than dropped so that argument 3 stays argument 3: the index into
 * this row is the index into the call's arguments.
 *
 * 91 of the 600 argument slots have a name.
 *
 * Read from the mcode definitions in ScummVM's `engines/sword1/logic.cpp`.
 */

/** Mcode number -> its six argument names, empty where the source has none. */
export const SWORD1_MCODE_PARAMS: readonly (readonly string[])[] = [
  ['', '', '', '', '', ''],
  ['', '', '', '', '', ''],
  ['', '', '', '', '', ''],
  ['', '', '', '', '', ''],
  ['walk_data', 'spr', '', '', '', ''],
  ['cdt', 'spr', '', '', '', ''],
  ['cdt', 'spr', 'frameNo', '', '', ''],
  ['anim', 'graphic', '', '', '', ''],
  ['cdt', 'spr', 'frameNo', '', '', ''],
  ['speed', '', '', '', '', ''],
  ['speed', '', '', '', '', ''],
  ['', '', '', '', '', ''],
  ['spritePal', '', '', '', '', ''],
  ['spritePal', '', '', '', '', ''],
  ['spritePal', '', '', '', '', ''],
  ['', '', '', '', '', ''],
  ['', '', '', '', '', ''],
  ['sequenceId', '', '', '', '', ''],
  ['', '', '', '', '', ''],
  ['pause', '', '', '', '', ''],
  ['pause', '', '', '', '', ''],
  ['', '', '', '', '', ''],
  ['target', '', '', '', '', ''],
  ['', '', '', '', '', ''],
  ['script', '', '', '', '', ''],
  ['script', '', '', '', '', ''],
  ['', '', '', '', '', ''],
  ['', '', '', '', '', ''],
  ['', '', '', '', '', ''],
  ['sendId', 'syncValue', '', '', '', ''],
  ['', '', '', '', '', ''],
  ['target', '', '', '', '', ''],
  ['target', 'script', '', '', '', ''],
  ['target', 'script', '', '', '', ''],
  ['target', '', '', '', '', ''],
  ['event', 'delay', '', '', '', ''],
  ['pause', '', '', '', '', ''],
  ['', '', '', '', '', ''],
  ['cdt', 'textNo', 'spr', '', '', ''],
  ['tar', 'instruc', 'param1', 'param2', 'param3', ''],
  ['tar', 'instruc', 'param1', 'param2', 'param3', ''],
  ['tar', '', '', '', '', ''],
  ['tar', 'width', 'pen', '', '', ''],
  ['', '', '', '', '', ''],
  ['target', '', '', '', '', ''],
  ['', '', '', '', '', ''],
  ['', '', '', '', '', ''],
  ['', '', '', '', '', ''],
  ['', '', '', '', '', ''],
  ['', '', '', '', '', ''],
  ['', '', '', '', '', ''],
  ['', '', '', '', '', ''],
  ['', '', '', '', '', ''],
  ['', '', '', '', '', ''],
  ['tag', 'rate', '', '', '', ''],
  ['tag', 'rate', '', '', '', ''],
  ['', '', '', '', '', ''],
  ['', '', '', '', '', ''],
  ['', '', '', '', '', ''],
  ['', '', '', '', '', ''],
  ['', '', '', '', '', ''],
  ['', '', '', '', '', ''],
  ['', '', '', '', '', ''],
  ['sub', '', '', '', '', ''],
  ['objectNo', '', '', '', '', ''],
  ['objectNo', '', '', '', '', ''],
  ['screen', '', '', '', '', ''],
  ['oldScreen', '', '', '', '', ''],
  ['floor', '', '', '', '', ''],
  ['x', 'y', 'dir', 'stance', '', ''],
  ['dir', 'stance', '', '', '', ''],
  ['dir', 'stance', '', '', '', ''],
  ['x', 'y', 'dir', 'stance', '', ''],
  ['targetId', '', '', '', '', ''],
  ['x', 'y', '', '', '', ''],
  ['targetId', '', '', '', '', ''],
  ['', '', '', '', '', ''],
  ['', '', '', '', '', ''],
  ['targetId', '', '', '', '', ''],
  ['', '', '', '', '', ''],
  ['fxNo', '', '', '', '', ''],
  ['fxNo', '', '', '', '', ''],
  ['tuneId', 'loopFlag', '', '', '', ''],
  ['', '', '', '', '', ''],
  ['', '', '', '', '', ''],
  ['min', 'max', '', '', '', ''],
  ['target', 'screen', '', '', '', ''],
  ['resId', '', '', '', '', ''],
  ['screen', '', '', '', '', ''],
  ['', '', '', '', '', ''],
  ['', '', '', '', '', ''],
  ['', '', '', '', '', ''],
  ['screen', 'resId', '', '', '', ''],
  ['', '', '', '', '', ''],
  ['', '', '', '', '', ''],
  ['', '', '', '', '', ''],
  ['', '', '', '', '', ''],
  ['', '', '', '', '', ''],
  ['', '', '', '', '', ''],
  ['', '', '', '', '', ''],
];

/** `'dir'` for argument 2 of `fnWalk`, or null where the source names none. */
export function sword1McodeParamName(mcode: number, index: number): string | null {
  const name = SWORD1_MCODE_PARAMS[mcode]?.[index];
  return name ? name : null;
}

/**
 * The eight compass directions by number, which is what a `dir` argument is.
 *
 * Generated from the same `sworddefs.h` the script ids come from, and checked
 * on generation to run 0..7 in that order — a rotated table would be an editor
 * that quietly turns every mega the wrong way.
 */
export const SWORD1_DIRECTION_NAMES: readonly string[] = [
  'up',
  'up-right',
  'right',
  'down-right',
  'down',
  'down-left',
  'left',
  'up-left',
];
