/**
 * GENERATED by `npm run gen:sword1-tables`. Do not edit by hand.
 *
 * The mcode table: what Broken Sword's bytecode calls each of its hundred
 * machine-code routines. `interpretScript` reads a *number* (`IT_MCODE`
 * carries the index and the argument count), so the names live in the
 * interpreter rather than in the game — ADR 0029's exact case for a table being
 * ours.
 *
 * The argument count is **not** here, and deliberately: Broken Sword encodes it
 * in the instruction beside the mcode number, so it is read rather than tabled.
 * That is what makes this family's bytecode splittable into instructions
 * without a table — the property `CONTEXT.md` calls out for the SCUMM Stack
 * encoding and for the PMachine, and the reason Decompilation is available here.
 *
 * Read from ScummVM's `engines/sword1/logic.cpp`.
 */

/** The hundred mcodes, indexed by the number `IT_MCODE` carries. */
export const SWORD1_MCODE_NAMES: readonly string[] = [
  'fnBackground',
  'fnForeground',
  'fnSort',
  'fnNoSprite',
  'fnMegaSet',
  'fnAnim',
  'fnSetFrame',
  'fnFullAnim',
  'fnFullSetFrame',
  'fnFadeDown',
  'fnFadeUp',
  'fnCheckFade',
  'fnSetSpritePalette',
  'fnSetWholePalette',
  'fnSetFadeTargetPalette',
  'fnSetPaletteToFade',
  'fnSetPaletteToCut',
  'fnPlaySequence',
  'fnIdle',
  'fnPause',
  'fnPauseSeconds',
  'fnQuit',
  'fnKillId',
  'fnSuicide',
  'fnNewScript',
  'fnSubScript',
  'fnRestartScript',
  'fnSetBookmark',
  'fnGotoBookmark',
  'fnSendSync',
  'fnWaitSync',
  'cfnClickInteract',
  'cfnSetScript',
  'cfnPresetScript',
  'fnInteract',
  'fnIssueEvent',
  'fnCheckForEvent',
  'fnWipeHands',
  'fnISpeak',
  'fnTheyDo',
  'fnTheyDoWeWait',
  'fnWeWait',
  'fnChangeSpeechText',
  'fnTalkError',
  'fnStartTalk',
  'fnCheckForTextLine',
  'fnAddTalkWaitStatusBit',
  'fnRemoveTalkWaitStatusBit',
  'fnNoHuman',
  'fnAddHuman',
  'fnBlankMouse',
  'fnNormalMouse',
  'fnLockMouse',
  'fnUnlockMouse',
  'fnSetMousePointer',
  'fnSetMouseLuggage',
  'fnMouseOn',
  'fnMouseOff',
  'fnChooser',
  'fnEndChooser',
  'fnStartMenu',
  'fnEndMenu',
  'cfnReleaseMenu',
  'fnAddSubject',
  'fnAddObject',
  'fnRemoveObject',
  'fnEnterSection',
  'fnLeaveSection',
  'fnChangeFloor',
  'fnWalk',
  'fnTurn',
  'fnStand',
  'fnStandAt',
  'fnFace',
  'fnFaceXy',
  'fnIsFacing',
  'fnGetTo',
  'fnGetToError',
  'fnGetPos',
  'fnGetGamepadXy',
  'fnPlayFx',
  'fnStopFx',
  'fnPlayMusic',
  'fnStopMusic',
  'fnInnerSpace',
  'fnRandom',
  'fnSetScreen',
  'fnPreload',
  'fnCheckCD',
  'fnRestartGame',
  'fnQuitGame',
  'fnDeathScreen',
  'fnSetParallax',
  'fnTdebug',
  'fnRedFlash',
  'fnBlueFlash',
  'fnYellow',
  'fnGreen',
  'fnPurple',
  'fnBlack',
];

/** How many mcodes the table declares. A call above this is a decoding fault. */
export const SWORD1_MCODE_COUNT = SWORD1_MCODE_NAMES.length;

/** `fnWalk` for 69, or `mcode69` when the number is outside the table. */
export function sword1McodeName(number: number): string {
  return SWORD1_MCODE_NAMES[number] ?? `mcode${number}`;
}
