/**
 * What each Lure script opcode number is called.
 *
 * **Generated by `npm run gen:lure-tables` — do not edit.** The names come
 * from the `S_OPCODE_*` defines in `engines/lure/scripts.h` in a ScummVM checkout, which
 * carry explicit values, so the number is read from the define rather than
 * inferred from order. The generator refuses a set with a gap in it.
 *
 * 26 opcodes. The index is the number the bytecode carries, **after
 * the has-parameter bit has been shifted off** — see `lureScript.ts`.
 */
export const LURE_OPCODE_NAMES: readonly string[] = [
  /*  0 */ 'abort',
  /*  1 */ 'add',
  /*  2 */ 'subtract',
  /*  3 */ 'multiply',
  /*  4 */ 'divide',
  /*  5 */ 'equals',
  /*  6 */ 'notEquals',
  /*  7 */ 'lt',
  /*  8 */ 'gt',
  /*  9 */ 'lte',
  /* 10 */ 'gte',
  /* 11 */ 'and',
  /* 12 */ 'or',
  /* 13 */ 'logicalAnd',
  /* 14 */ 'logicalOr',
  /* 15 */ 'getField',
  /* 16 */ 'setField',
  /* 17 */ 'push',
  /* 18 */ 'subroutine',
  /* 19 */ 'exec',
  /* 20 */ 'end',
  /* 21 */ 'condJump',
  /* 22 */ 'jump',
  /* 23 */ 'abort2',
  /* 24 */ 'abort3',
  /* 25 */ 'random',
];

/** `LURE_OPCODE_NAMES.length`, named for the bound checks that want it. */
export const LURE_OPCODE_COUNT = 26;

/** The opcode's name, or a number in angle brackets where there is none. */
export function lureOpcodeName(opcode: number): string {
  return LURE_OPCODE_NAMES[opcode] ?? `<opcode ${opcode}>`;
}
